name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: msfjarvis/setup-android@0.2
      with:
    # Gradle tasks to run - If you want to run ./gradlew assemble, specify assemble here. 
        gradleTasks: assembleDebug
